### ISSUE TITLE
colspan

### ISSUE THREAD

**Issue by OlegRozman** [kamack38/cheatsheet-template#1]
``` typst
show table.cell.where(y: 0): it => {
    table.cell(colspan: 2)[#it]
  }
```

it doesn't work

**Comment by kamack38** [comment]
Could you elaborate and provide an example?

**Comment by OlegRozman** [comment]
insert this code into your template:
`table.header[#lorem(30)],`

**Comment by kamack38** [comment]
> insert this code into your template:
> `table.header[#lorem(30)],`

I think that's because the table.header doesn't support the `colspan` property. I'll try to fix it next week. In the meantime you can copy the template to your code and replace the `table.header` with `table.cell` yourself.
